In [1]:
import SimpleITK as sitk

# Define the directory containing the DICOM series
dicom_directory = "../assets/trial/CT_Facial_20230421_154425"

# Create an ImageSeriesReader object
reader = sitk.ImageSeriesReader()

# Get the list of DICOM file names in the directory
dicom_filenames = reader.GetGDCMSeriesFileNames(dicom_directory)

# Set the file names to the reader
reader.SetFileNames(dicom_filenames)

# Read the image
image = reader.Execute()

# Optionally, you can print some information about the image
print(f"Image size: {image.GetSize()}")
print(f"Image spacing: {image.GetSpacing()}")
print(f"Image direction: {image.GetDirection()}")
print(f"Image origin: {image.GetOrigin()}")

# Save the image to a file (optional)
# sitk.WriteImage(image, "output_image.nii")


Image size: (666, 666, 666)
Image spacing: (0.3, 0.3, 0.3)
Image direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
Image origin: (-99.9, -99.9, -200.0)


In [11]:
import SimpleITK as sitk

image_path = '../assets/data_set/S0000000001/S0000000001.nii.gz'
landmark_path = '../assets/data_set/S0000000001/S0000000001_landmark_mask.nii.gz'
image_vol = sitk.ReadImage(image_path)
landmark_vol = sitk.ReadImage(landmark_path)

In [12]:
print(f"Image size: {image_vol.GetSize()}")
print(f"Image spacing: {image_vol.GetSpacing()}")
print(f"Image direction: {image_vol.GetDirection()}")
print(f"Image origin: {image_vol.GetOrigin()}")

Image size: (666, 666, 666)
Image spacing: (0.30000001192092896, 0.30000001192092896, 0.30000001192092896)
Image direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
Image origin: (-99.9000015258789, -99.9000015258789, -200.0)


In [13]:
print(f"Image size: {landmark_vol.GetSize()}")
print(f"Image spacing: {landmark_vol.GetSpacing()}")
print(f"Image direction: {landmark_vol.GetDirection()}")
print(f"Image origin: {landmark_vol.GetOrigin()}")

Image size: (666, 666, 666)
Image spacing: (0.30000001192092896, 0.30000001192092896, 0.30000001192092896)
Image direction: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)
Image origin: (-99.9000015258789, -99.9000015258789, -200.0)


In [14]:
origin_target = (0,0,0)
dir_target = (-1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0)

In [15]:
image_vol.SetOrigin(origin_target)
# image_vol.SetDirection(dir_target)

In [16]:
landmark_vol.SetOrigin(origin_target)
# landmark_vol.SetDirection(dir_target)

In [17]:
img_output_path = "./S0000000001_mod2_origin.nii.gz"
landmark_output_path = "./S0000000001_mod_landmark_origin.nii.gz"

In [30]:
import numpy as np

transformed_to_origin = np.array([42.4578742980957,7.314310073852539,-169.0973358154297])-np.array([-99.9000015258789, -99.9000015258789, -200.0])
print(transformed_to_origin)
world_coordinates = np.array(transformed_to_origin) #train.csv data
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

[142.35787582 107.2143116   30.90266418]
(475, 357, 103)


In [31]:
transformed_to_origin = np.array([2.0241801738739014,-44.08097839355469,-198.08265686035156])-np.array([-99.9000015258789, -99.9000015258789, -200.0])
print(transformed_to_origin)
world_coordinates = np.array(transformed_to_origin) #train.csv data
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

[101.9241817   55.81902313   1.91734314]
(340, 186, 6)


In [32]:
transformed_to_origin = np.array([2.958989381790161,-4.443952560424805,-196.82406616210938])-np.array([-99.9000015258789, -99.9000015258789, -200.0])
print(transformed_to_origin)
world_coordinates = np.array(transformed_to_origin) #train.csv data
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

[102.85899091  95.45604897   3.17593384]
(343, 318, 11)


In [18]:
import os
os.getcwd()

'/home/sankar/VSCODE_PROJECTS/Medical-Detection3d-Toolkit/notebooks'

In [19]:
sitk.WriteImage(image_vol, img_output_path)

In [20]:
sitk.WriteImage(landmark_vol, landmark_output_path)

In [7]:
img_origin_original = image_vol.GetOrigin()
img_origin_target = (0,0,0)

In [9]:
image_vol.SetOrigin(img_origin_target)

In [ ]:
world_coordinates = (2.0241801738739014,-44.08097839355469,-198.08265686035156) #train.csv data
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

In [ ]:
import SimpleITK as sitk

# Load the image
image = sitk.ReadImage(image_path, sitk.sitkFloat32)

# Print the original origin and direction
print("Original Origin:", image.GetOrigin())
print("Original Direction:", image.GetDirection())

# Set new origin and direction
image.SetOrigin((0, 0, 0))
image.SetDirection((-1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0))

# Specify the path where you want to save the modified image
output_path = "/path/to/save/modified_image.nii.gz"

# Save the modified image
sitk.WriteImage(image, output_path)

print("Modified image saved to:", output_path)


In [4]:
world_coordinates = (2.0241801738739014,-44.08097839355469,-198.08265686035156) #train.csv data
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

(340, 186, 6)


In [3]:
# image_vol.SetOrigin((99.9000015258789, 99.9000015258789, -200.0))
# image_vol.SetDirection((-1., 0, 0, 0, -1., 0, 0, 0, 1.))
# image_vol.SetSpacing((1., 1., 1.))

Converting Landmark LPS Coordinate to Voxel Coordinate

In [4]:
import csv
import pandas as pd

# Define the path to your .fcv file
fcv_file_path = '../assets/trial/skeletal phenotype landmarks 20230421 000009903.fcsv'

# Initialize an empty dictionary to hold the nested dictionaries
data_dict = {}

# Variable to hold the coordinate system
coordinate_system = None

# Open the file and read its content
with open(fcv_file_path, 'r') as f:
    reader = csv.reader(f)
    
    # Skip the header lines and extract the coordinate system
    for line in reader:
        if line[0].startswith('#'):
            if 'CoordinateSystem' in line[0]:
                coordinate_system = line[0].split('=')[1].strip()
            continue
        
        # Extract the relevant columns and create nested dictionary
        label = line[11]
        data_dict[label] = {
            # 'id': line[0],
            'L': float(line[1]),
            'P': float(line[2]),
            'S': float(line[3]),
            # 'coordinate_system': coordinate_system
        }

# Convert the nested dictionary to a list of dictionaries
data_list = [{'label': label, **data} for label, data in data_dict.items()]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(data_list)

# Print the DataFrame
print(df)


   label    L          P           S
0     C3  0.0  18.242038 -183.269615
1    RGn  0.0 -38.942067 -185.967954
2  Hyoid  0.0  -2.652714 -196.813048


In [5]:
df[df['label']=='C3'].iloc[:,1:].values[0]

array([   0.        ,   18.24203768, -183.26961451])

In [6]:
world_coordinates = df[df['label']=='C3'].iloc[:,1:].values[0]
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

(333, 394, 56)


In [7]:
world_coordinates = df[df['label']=='RGn'].iloc[:,1:].values[0]
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

(333, 203, 47)


In [8]:
world_coordinates = df[df['label']=='Hyoid'].iloc[:,1:].values[0]
voxel_coordinates = image_vol.TransformPhysicalPointToIndex(world_coordinates)
print(voxel_coordinates)

(333, 324, 11)


In [ ]:
import os

# Define the directory containing the files
folder_path = "../assets/trial/CT_Facial_20230421_154425"

# List all files in the directory
files_in_folder = os.listdir(folder_path)

# Loop through all files
for file_name in files_in_folder:
    # Check if the file has a .dcm extension
    if not file_name.endswith('.dcm'):
        # If not, remove the file
        file_path = os.path.join(folder_path, file_name)
        os.remove(file_path)
        print(f"Removed file: {file_path}")

print("Cleanup complete.")
